### ISSUE TITLE
1920x1200 resolution support

### ISSUE THREAD

**Issue by TimonVS** [networkprogrammer/bing-wallpaper-for-mac#1]
You can actually get the 1920x1200 version by changing 1920x1080 in the image url to 1920x1200, e.g.: http://www.bing.com/az/hprichbg/rb/FrogSibs_EN-US11029023450_1920x1200.jpg.

1920x1200 is obviously much nicer for 16:10 screens because you'll avoid cropping the image.

**Comment by networkprogrammer** [comment]
I have been trying to get the json url for this image. I would much rather have the image from the source instead of switching the url on the fly. Thanks, Let me update the code.

**Comment by networkprogrammer** [comment]
I have updated the code to use the new url. 
Thanks!
