### ISSUE TITLE
Multiple monitors support

### ISSUE THREAD

**Issue by gtdeng** [networkprogrammer/bing-wallpaper-for-mac#10]
Hi. I've been using it on my osx for months now and love it everyday. Thanks for creating this! I believe what would make this better would be to incorporate multiple monitors support. Currently, only the main screen's wallpaper is updated. I've looked into osx preferences to no avail. Thanks!

**Comment by networkprogrammer** [comment]
Hello,
I am not sure if anything has changed with OSX Sierra, but last time I looked into this, there was no way to do this. If you find any solution, please contribute or send me the info. I'll try to fix it. My google search came up empty.
