### ISSUE TITLE
external display

### ISSUE THREAD

**Issue by j67678** [networkprogrammer/bing-wallpaper-for-mac#3]
how to set as external display wallpaper, too?

**Comment by networkprogrammer** [comment]
Sorry for the late reply. Can you elaborate on external display?

**Comment by gaberber** [comment]
I don't know if it's the same problem, but the "Set Desktop Picture" function in Automator (and, in fact, in the System Preferences manual selection panel, too) only changes the picture of the workspace currently being displayed. If you have multiple virtual desktops (workplaces) or external displays, the other desktop pictures will not be affected by this change. 
I googled a bit on this problem but found no solution. It seems the only possible workaround is to `killall Dock` and force the change of desktop picture to apply to all desktops and external displays, which I am very reluctant to do. But I doubt there would be any good solution until Apple provides us with an "apply to all desktops" option.

**Comment by networkprogrammer** [comment]
@gaberber You are right, I could not find a good solution that would allow the script to set the wp on all desktops. 

@renzhn I shall close this issue as there are no solutions out today that I am aware of. Please feel free to update/share any information you come across that can enhance this project.
