### ISSUE TITLE
pointing to python script

### ISSUE THREAD

**Issue by ghost** [networkprogrammer/bing-wallpaper-for-mac#5]
Assuming the user has placed "Bing Wallpaper" folder inside of /Applications and not /Users/USERNAME/Applications the automator script should direct to /Applications not ~/Applications

**Comment by networkprogrammer** [comment]
Hi @Foxrida56, yes if the location of the folder changes, the script would need to be modified to point to that. I believe the reason I put it in ~/Applications to begin with is that some users find that they do not have enough permissions to execute scripts and make changes to /Applications.

Thanks.
