### ISSUE TITLE
Multiple Monitors

### ISSUE THREAD

**Issue by marcsfussell** [networkprogrammer/bing-wallpaper-for-mac#6]
What would I need to change to make it update the background on my external monitors as well?  It is properly changing the backgound on my laptop primary display, but I also have a Apple monitor connected that I would like to be updated as well.

Cool script, BTW.

**Comment by networkprogrammer** [comment]
Hi @marcsfussell, There was another issue regarding the same problem and it looks like Apple today does not provide a way to assign wallpapers to all desktops, at least not through automator. 

Let me know if you come across a way to do so and I will gladly add it to the script.

Thanks,
