### ISSUE TITLE
Battery usage

### ISSUE THREAD

**Issue by jdrobert** [networkprogrammer/bing-wallpaper-for-mac#7]
Since I set this to run automatically using `launchctl load ~/Library/LaunchAgents/bing.wallpaper.mac.plist` the battery life on my MacBook Air has been cut in half or more. 

I ran the uninstall command while I had 11 minutes of battery remaining at 9%. Now I'm at 9% with 34 minutes remaining.  

Since it only works once a day, can you make the background task only run once a day?

**Comment by Fofer** [comment]
According to [this note](https://www.reddit.com/r/osx/comments/3187bq/bing_wallpaper_for_mac/cq07a3r), the plist on the repo is already set to run once a day, at 8 am, and that time can be adjusted as desired.

Given the nature of what this script does -- which is simply fetch the Bing wallpaper image, and make it a desktop pattern -- I'm skeptical that it's really the cause of your battery issue.

**Comment by jdrobert** [comment]
By default the app is set to run every 3600 seconds (1 hour). I didn't know that I could set the run time manually. Thanks for pointing that out. 

``` xml
<!-- This is to run the app at specified intervals -->
<!-- -->
    <key>StartInterval</key>
      <integer>3600</integer>
```

https://github.com/networkprogrammer/bing-wallpaper-for-mac/blob/master/bing.wallpaper.mac.plist

While I agree that running once an hour shouldn't do this to my battery, it has been much better since running the unload command. It could be some other app but this is the last thing I installed.

**Comment by networkprogrammer** [comment]
@jdrobert @Fofer Thanks for looking into this. Yes, this code does not do anything until it is invoked by the system. I preferred this method to having a process always running.

I believe that the battery issue could have been a combination of a lot if things on your machine. Invoking the script could have added to the load, but once the job is done, the script would not affect your battery life.

That being said, I'll close out this issue.
Thanks,
