### ISSUE TITLE
Option to not delete the image daily?

### ISSUE THREAD

**Issue by Sayant** [networkprogrammer/bing-wallpaper-for-mac#9]
Hi, is there any option easily enabled to keep the images for previous days?  I'd rather clean out the folder manually rather than lose some really great images...

**Comment by Fofer** [comment]
https://www.reddit.com/r/osx/comments/3187bq/bing_wallpaper_for_mac/cq160cx

You can open the "BingWallpaper" app in Automator, and edit how the previous images are handled.
